// <auto-generated />
using System;
using ClearChain.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClearChain.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClearChain.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entityid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entitytype");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text")
                        .HasColumnName("ipaddress");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("newvalue");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("oldvalue");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("useragent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Id");

                    b.ToTable("auditlogs", (string)null);
                });

            modelBuilder.Entity("ClearChain.Domain.Entities.ClearanceListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("ClearanceDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("clearancedeadline");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirationdate");

                    b.Property<Guid>("GroceryId")
                        .HasColumnType("uuid")
                        .HasColumnName("groceryid");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("groupid");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photourl");

                    b.Property<Guid?>("PickupRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickuprequestid");

                    b.Property<TimeSpan?>("PickupTimeEnd")
                        .HasColumnType("interval")
                        .HasColumnName("pickuptimeend");

                    b.Property<TimeSpan?>("PickupTimeStart")
                        .HasColumnType("interval")
                        .HasColumnName("pickuptimestart");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("productname");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("RelatedRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("relatedrequestid");

                    b.Property<Guid?>("SplitFromListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("splitfromlistingid");

                    b.Property<int>("SplitIndex")
                        .HasColumnType("integer")
                        .HasColumnName("splitindex");

                    b.Property<string>("SplitReason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("splitreason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id");

                    b.HasIndex("GroceryId");

                    b.HasIndex("GroupId");

                    b.ToTable("clearancelistings", (string)null);
                });

            modelBuilder.Entity("ClearChain.Domain.Entities.FCMToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizationid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("fcmtokens", (string)null);
                });

            modelBuilder.Entity("ClearChain.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime?>("DistributedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("distributedat");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirydate");

                    b.Property<Guid>("NgoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ngoid");

                    b.Property<Guid>("PickupRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pickuprequestid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("productname");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("receivedat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id");

                    b.ToTable("inventory", (string)null);
                });

            modelBuilder.Entity("ClearChain.Domain.Entities.ListingGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("ClearanceDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("clearancedeadline");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expirationdate");

                    b.Property<Guid>("GroceryId")
                        .HasColumnType("uuid")
                        .HasColumnName("groceryid");

                    b.Property<bool>("IsFullyConsumed")
                        .HasColumnType("boolean")
                        .HasColumnName("isfullyconsumed");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("OriginalListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("originallistingid");

                    b.Property<decimal>("OriginalQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("originalquantity");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photourl");

                    b.Property<TimeSpan?>("PickupTimeEnd")
                        .HasColumnType("interval")
                        .HasColumnName("pickuptimeend");

                    b.Property<TimeSpan?>("PickupTimeStart")
                        .HasColumnType("interval")
                        .HasColumnName("pickuptimestart");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("productname");

                    b.Property<decimal>("TotalAvailable")
                        .HasColumnType("numeric")
                        .HasColumnName("totalavailable");

                    b.Property<decimal>("TotalCompleted")
                        .HasColumnType("numeric")
                        .HasColumnName("totalcompleted");

                    b.Property<decimal>("TotalReserved")
                        .HasColumnType("numeric")
                        .HasColumnName("totalreserved");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.HasKey("Id");

                    b.HasIndex("GroceryId");

                    b.ToTable("listinggroups", (string)null);
                });

            modelBuilder.Entity("ClearChain.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("authprovider");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text")
                        .HasColumnName("googleid");

                    b.Property<string>("Hours")
                        .HasColumnType("text")
                        .HasColumnName("hours");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("profilepictureurl");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verificationstatus");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("ClearChain.Domain.Entities.PickupRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ConfirmedReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmedreceivedat");

                    b.Property<Guid>("GroceryId")
                        .HasColumnType("uuid")
                        .HasColumnName("groceryid");

                    b.Property<string>("ListingCategory")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("listingcategory");

                    b.Property<Guid?>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listingid");

                    b.Property<string>("ListingTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("listingtitle");

                    b.Property<DateTime?>("MarkedPickedUpAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("markedpickedupat");

                    b.Property<DateTime?>("MarkedReadyAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("markedreadyat");

                    b.Property<Guid>("NgoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ngoid");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pickupdate");

                    b.Property<string>("PickupTime")
                        .HasColumnType("text")
                        .HasColumnName("pickuptime");

                    b.Property<string>("ProofPhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("proofphotourl");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requestedat");

                    b.Property<int?>("RequestedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("requestedquantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("GroceryId");

                    b.HasIndex("NgoId");

                    b.ToTable("pickuprequests", (string)null);
                });

            modelBuilder.Entity("ClearChain.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiresat");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("isrevoked");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizationid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revokedat");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("refreshtokens", (string)null);
                });

            modelBuilder.Entity("pickuprequestlistings", b =>
                {
                    b.Property<Guid>("listingid")
                        .HasColumnType("uuid")
                        .HasColumnName("listingid");

                    b.Property<Guid>("pickuprequestid")
                        .HasColumnType("uuid")
                        .HasColumnName("pickuprequestid");

                    b.HasKey("listingid", "pickuprequestid");

                    b.HasIndex("pickuprequestid");

                    b.ToTable("pickuprequestlistings");
                });

            modelBuilder.Entity("ClearChain.Domain.Entities.ClearanceListing", b =>
                {
                    b.HasOne("ClearChain.Domain.Entities.Organization", "Grocery")
                        .WithMany()
                        .HasForeignKey("GroceryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearChain.Domain.Entities.ListingGroup", "Group")
                        .WithMany("ChildListings")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Grocery");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ClearChain.Domain.Entities.FCMToken", b =>
                {
                    b.HasOne("ClearChain.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ClearChain.Domain.Entities.ListingGroup", b =>
                {
                    b.HasOne("ClearChain.Domain.Entities.Organization", "Grocery")
                        .WithMany()
                        .HasForeignKey("GroceryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grocery");
                });

            modelBuilder.Entity("ClearChain.Domain.Entities.PickupRequest", b =>
                {
                    b.HasOne("ClearChain.Domain.Entities.Organization", "Grocery")
                        .WithMany()
                        .HasForeignKey("GroceryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearChain.Domain.Entities.Organization", "Ngo")
                        .WithMany()
                        .HasForeignKey("NgoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grocery");

                    b.Navigation("Ngo");
                });

            modelBuilder.Entity("ClearChain.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ClearChain.Domain.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("pickuprequestlistings", b =>
                {
                    b.HasOne("ClearChain.Domain.Entities.ClearanceListing", null)
                        .WithMany()
                        .HasForeignKey("listingid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClearChain.Domain.Entities.PickupRequest", null)
                        .WithMany()
                        .HasForeignKey("pickuprequestid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClearChain.Domain.Entities.ListingGroup", b =>
                {
                    b.Navigation("ChildListings");
                });
#pragma warning restore 612, 618
        }
    }
}
